### ISSUE TITLE
Modify HTC Driver downloader to direct user to an XDA-Dev forum for manual download instead?

### ISSUE THREAD

**Issue by gbakeman** [squabbi/HTCOneM8Toolkit#4]
Currently it looks like the file the toolkit tries to download doesn't exist. I wonder if the HTC Driver downloader function should be modified instead to direct the user to an XDA-Dev forum topic (this looks like the latest version: http://forum.xda-developers.com/showthread.php?t=2535581) and have them manually run the installer, then the toolkit can check to see that the drivers are installed and go from there. This helps eliminate the risk of a hard-coded file disappearing in the future, so the user can search for it instead. Unless we include the installer with the distribution, but I don't know how licensing would work in that situation.

**Comment by squabbi** [comment]
I do have the msi hosted on basketbuild which I can get a direct link for. https://s.basketbuild.com/dl/devs?dl=squabbi/HTCDriver.msi

I've also worked on a refresh of the HTC One M9 toolkit which has features from my recent releases. I might be able to get that up and running easier.

Edit: I duplicated an existing project and made it fit for the M8. Please feel free to contribute here: https://github.com/squabbi/HTCOneM8Toolkit2

**Comment by gbakeman** [comment]
Just saw your post on XDADev, I was going to ask if it would make sense to maybe standardize some of the toolkits to reduce duplication of efforts. Thanks :)
